### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [vr8hub/h-rider-haggard_she#1]
1. In chapter 3 there are abbreviated units (lb and oz) but are missing `<abbr>`s and trailing periods. [Manual 8.8.6.4.2](https://standardebooks.org/manual/1.0.0/8-typography#8.8.6.4.2)

2. Also in chapter 3, there is a latin name that was left capitalized and missing a period:
 `<b><abbr class="name">C.</abbr> FVFIDIVS <abbr class="name">C. F.</abbr> VINDEX</b>`
It should look like this:
`<b><abbr class="name">C.</abbr> <abbr class="name">Fvfidivs.</abbr> <abbr class="name">C. F.</abbr> Vindex</b>`

3. The medieval Latin translations in chapter 3 are missing language tags.

4. In the local.css you have:
```
/* temporary for proofreading */
blockquote{
	font-size: 93%;
	margin-left: 1.5em;
	margin-right: 1.5em;
}
```
Did you mean to leave this in?

5. In the dedication, since this is one clause broken into lines, a single `<p>` broken with `<br/>`s would be appropriate. To just target "Andrew Lang" you can wrap it with `<b>`. [Manual 1.1.6](https://standardebooks.org/manual/1.0.0/1-code-style#1.1.6)
xhtml:
```
<p>I inscribe this history to<br/>
<b>Andrew Lang</b><br/>
...
```
local.css:
```
/* custom dedication CSS */
[epub|type~="dedication"] p{
	text-indent: 0;
	text-align: center;
}

[epub|type~="dedication"] b{
	text-transform: uppercase;
}
/* end of dedication */
```

6. Lint is complaining about an unused se-lint-ignore.xml rule for introduction.xhtml.

7. The colophon is missing `<abbr class="name">` for H. Rider Haggard.

8. Where is your List of Illustrations? [Manual 7.9](https://standardebooks.org/manual/1.0.0/7-high-level-structural-patterns#7.9)

**Comment by vr8hub** [comment]
1. Yep, looked right past them since they were in the caption. Fixed.
2. Great catch, fixed.
3. Doh! Got the Greek, missed the Latin. Fixed.
4. No I did not. :) Removed.
5. The manual does not say that dedications have to use breaks. It doesn't mention formatting at all in the Dedication section, except to say it's OK to match what's in the source. Since there was no markup in this dedication, it doesn't matter whether it uses p or br. But, since this isn't a hill I'm going to die on, so I changed it. But unless they're violating something else in the manual, it doesn't really matter how someone formats the dedication.
6. Right, I'm on a new version of the tools than you are. (An "in-between" version, if you will.) It's an error here, so I left it in.
7. Hmmm. I don't think I realized the colophon needed abbreviations. Fixed.
8. Wow, totally spaced on that one. That should be a lint check, I'll look into that. Fixed. This in turn required illustrators to be put in content, the URL changed, etc. There were two illustrators mentioned in the source, and since I don't know which did the three pictures we used, I put them both in. My repository URL no longer matches the internal one in content/colophon, but it shouldn't matter; Alex will create the correct URL in SE when he publishes it.

Thanks, Emma, great eye! I still haven't heard definitively who should close the review issues, so I'm leaving it to you to confirm I did what I said and then close it. :)
